language: node_js

node_js:
- '0.10'

before_script: npm install -g codeclimate-test-reporter

after_script:
- cat coverage/lcov.info | codeclimate

addons:
  code_climate:
    repo_token:
       secure: E0+mP3C7FJoltiGlzrrB7QpQmNITUqbHnK2VT5tHpiCVlfBCyQ9gvx7kBnMVCpk4DsEyj84L3ymrKmqILaCo21qxn72vac8nwBTsySDadpPfzsGYhV9h9WjUM5nv4HdBBjWX/Qgn2vBwL+zdQ18iL/WjtIxPd054u/CptMisyMc=
